apiVersion: batch/v1
kind: Job
metadata:
  namespace: studbernstetter
  name: elmo-germanweights
spec:
  template:
    metadata:
      name: elmo-germanweights
    spec:
      containers:
      - name: elmo-germanweights
        image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/mprak/bilmtfcuda10
        imagePullPolicy: "Always"
        resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: "2"
            memory: "32Gi"
          requests:
            nvidia.com/gpu: "1"
            cpu: "1"
            memory: "32Gi"
        volumeMounts:
        - mountPath: "/super_corpus"
          name: corpus
        command: ["bash", "-c", "python bin/dump_weights.py --save_dir /super_corpus/outputcuda10 --outfile /super_corpus/outputcuda10/weights-20190705.hdf5"]
        #command: ["bash", "-c", "python3 datasets/openwebtext/create_tfrecords.py && python3 main.py --model 1.5B.json"]
      restartPolicy: "OnFailure"
      imagePullSecrets:
      - name: gitlab-registry
      volumes:
      - name: corpus
        cephfs:
          monitors:
          - 132.187.14.5,132.187.14.6,132.187.14.7,132.187.14.8,132.187.14.10
          user: studbernstetter
          path: "/home/stud/bernstetter/super_corpus/"
          secretRef:
            name: ceph-secret-studbernstetter
