apiVersion: batch/v1
kind: Job
metadata:
  namespace: studbernstetter
  name: evalminimal
spec:
  template:
    metadata:
      name: evalminimal
    spec:
      containers:
      - name: evalminimal
        image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/mprak/bilmtfminimal
        imagePullPolicy: "Always"
        resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: "2"
            memory: "32Gi"
          requests:
            nvidia.com/gpu: "1"
            cpu: "1"
            memory: "32Gi"
        volumeMounts:
        - mountPath: "/minimal_corpus"
          name: corpus
        command: ["bash", "-c", "python3 bin/run_test.py --test_prefix=\"/minimal_corpus/heldout/*\" --vocab_file /minimal_corpus/min_vocab.txt --save_dir /minimal_corpus/outputcopy"]
        #command: ["bash", "-c", "python3 datasets/openwebtext/create_tfrecords.py && python3 main.py --model 1.5B.json"]
      restartPolicy: "OnFailure"
      imagePullSecrets:
      - name: gitlab-registry
      volumes:
      - name: corpus
        cephfs:
          monitors:
          - 132.187.14.5,132.187.14.6,132.187.14.7,132.187.14.8,132.187.14.10
          user: studbernstetter
          path: "/home/stud/bernstetter/minimal_corpus/"
          secretRef:
            name: ceph-secret-studbernstetter
